version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
            - dbt_expectations.expect_column_distinct_count_to_equal:
                value: 4
              # quote_values: true # (Optional. Default is 'true'.)
              # group_by: [group_id, other_group_id, ...] # (Optional)
              # row_condition: "id is not null" # (Optional)
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"
                  # row_condition: "id is not null" # (Optional)
                  # is_raw: True # (Optional)
                  # flags: i # (Optional)

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}

      - name: hosts
        identifier: raw_hosts

      